version: "3.8"
services:
  container-tracker:
    image: bltwcp/container-tracker:v1.1.7.1
    restart: always
    ports:
      - 30111:80
    environment:
      - ASPNETCORE_ENVIRONMENT=PreProduction
    volumes:
    - ~/docker/ctn-test/appsettings.PreProduction.json:/app/appsettings.PreProduction.json